language: cpp
compiler: gcc
sudo: required
dist: trusty


before_install: 
  - wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_14.04/ /' >/tmp/hpcoders.list 
  - sudo mv /tmp/hpcoders.list /etc/apt/sources.list.d/
  - sudo apt-get update -qq
  - ./build_and_install_deps.sh
script: 
  - make
  - Xvfb :0 &
  - export DISPLAY=:0
  - make sure
